### ISSUE TITLE
Does it really require wayland-git and libinput-git on Arch?

### ISSUE THREAD

**Issue by actionless** [Cloudef/loliwm#54]
i tried to build it with:
```
extra/wayland 1.6.0-1
extra/libinput 0.7.0-1
```
and can't notice any behavior difference or glitches

will it make sense to modify (or create another) PKGBUILD for such case?

P.S. i build wlc-git with those lib versions as well

**Comment by Cloudef** [comment]
wlc is developed against wayland-git, so it's recommended to use git versions. Especially xdg-shell breaks from time to time, but it's getting more stable.

**Comment by Earnestly** [comment]
You're invited to modify PKGBUILDs for your own needs but the `-git` dependencies are to make it clear that the API is unstable and, on many occasions in the past, building wlc against repo versions of wayland caused build failures and may cause failure in the future again.

As @Cloudef said, this will stabilise eventually and the `-git` requirements will drop.

**Comment by actionless** [comment]
thanks for the exaplnations, guys!
