### ISSUE TITLE
loliwm instantly exits on vnc

### ISSUE THREAD

**Issue by 5paceToast** [Cloudef/loliwm#59]
The goal is to launch loliwm on a vnc-xdisplay and later view it through that.
However, wlc reports that loliwm exits... immediately after it starts (vnc log may be seen [here](http://sprunge.us/NINb)).
I can send my xstartup and loliwm startup system if it's needed.

**Comment by Cloudef** [comment]
Well, the log seems fine. How do you start it?

**Comment by 5paceToast** [comment]
Loliwm was installed the following way:
mkdir -p ~/.bin/loliwm_prefix && cd ~/.bin/loliwm
git clone (...) src && cd src
mkdir build && cd build
cmake .. && make -j4

This script is then placed into loliwm_prefix: [source](http://sprunge.us/JJBd)
Symbolically linked into ~/.bin/loliwm

Loliwm is then launched by running "loliwm" (with ~/.bin being in PATH).

I've used this sort of setup for many other self-compiled projects...

Source of xstartup (for vnc): [here](http://sprunge.us/bLCj)
Source of exports.sh: [here](http://sprunge.us/UHHF) (to make programs with support launch through wayland).

**Comment by ld-cd** [comment]
Do you have suid set on the binary (owner has to be root)

**Comment by 5paceToast** [comment]
I have not, but after doing that, result is the same.

**Comment by ld-cd** [comment]
chmod ug+s should set suid correctly. Did you compile and install wlc separately, if you did it sometimes installs to /usr/local/lib, which isn't always in libdir. Try running loliwm like this "loliwm 2> somefile", and then posting the contents.

**Comment by 5paceToast** [comment]
If you read the above, it's compiled from git in $HOME/.bin/loliwm_prefix/src and not installed at all.
Exact same issue after reapplying suid.
Please see the links posted above for the debug output of wlc, how loliwm was installed etc.

**Comment by ld-cd** [comment]
Sorry i didn't look closely enough at your post. It says parent exited in the log, that might mean vnc or sh stopped.

**Comment by 5paceToast** [comment]
The parent means loliwm, afaik (since wlc is what outputs it).
VNC does not exit (I can connect to it, there's just nothing there).
Not sure how sh would matter in an "exec" statement.....

**Comment by ld-cd** [comment]
good points (sorry I'm a bit of a noob), it looks like after a quick glance through fd.c (wlc) it looks like drm_load is exiting immediately, causing the function communicate to run, which seems to be the thing causing the exit of the whole program.

**Comment by ld-cd** [comment]
I think its probably just not loading in a way we don't expect it to not load

**Comment by ld-cd** [comment]
my guess would be that by resetting LD_LIBRARY_PATH your making it impossible to find libdrm.so, and therefore breaking that piece of code (line 72 in fd.c).

**Comment by Cloudef** [comment]
The parent exit comes from the FD passing fork that runs as suid or sgid permissions (depending if you need TTY switching or not), opening and closing fds for the compositor and handling drm master and drops permissions. Parent exit also means that the fd fork noticed that the main process died. The strange thing is that it seems to die normally, without anything in log. (I may bail out somewhere without logging, I guess?)

@ld-cd Should the drm_load function print out error if that particular line failed? I don't see any references in the log.

@5paceToast Can you check with gdb that the process actually exits normally.

**Comment by 5paceToast** [comment]
I checked loliwm's RPATH and it matched the LD_LIBRARY_PATH.
Trying to run it w/o LD_LIBRARY_PATH (so relying on the executable's built-in rpath) still has the same issue.

**Comment by 5paceToast** [comment]
GDB results - interesting:
```
Program received signal SIGFPE, Arithmetic exception.
[Switching to Thread 0x7fd1a0dee700 (LWP 5869)]
```
-----------------------------
backtrace:
```
#0  0x00007fd19f9b5b4e in ?? ()
#1  0x3a8888883a888888 in ?? ()
#2  0x3a8888883a888888 in ?? ()
#3  0x3a8888883a888888 in ?? ()
#4  0x3a8888883a888888 in ?? ()
#5  0x3b0888883b088888 in ?? ()
#6  0x3b0888883b088888 in ?? ()
#7  0x3b0888883b088888 in ?? ()
#8  0x3b0888883b088888 in ?? ()
#9  0x0000000000000000 in ?? ()
```

**Comment by Cloudef** [comment]
Seems like something somewhee is causing sigfpe, wlc catches those in debug builds. Either build with release or set WAYLAND_DISPLAY to something to workaround this. (Also make sure your DISPLAY is set to correct X server, though if you use startx/xinit, it should do it correctly).

**Comment by 5paceToast** [comment]
Building in release fixes all of my previous issues.
There goes the hope of debugging~

**Comment by ids1024** [comment]
I am also getting SIGFPE with orbment (fixed by using a release build).
