### ISSUE TITLE
mpv doesn’t scale correctly

### ISSUE THREAD

**Issue by linkmauve** [Cloudef/loliwm#71]
Whether it is launched windowed or fullscreen, it needs to be resized before the vo selects the best rendering resolution to fit the surface given to it, resulting in a blurry or pixellized image at its first resolution.

**Comment by Cloudef** [comment]
Same as #73

**Comment by Cloudef** [comment]
Not same as #73, however this bug is fixed and fixes bemenu not appearing randomly as well.
