### ISSUE TITLE
GLX fails at getting a context

### ISSUE THREAD

**Issue by linkmauve** [Cloudef/loliwm#74]
glxinfo says “Error: couldn't find RGB GLX visual or fbconfig”

**Comment by Cloudef** [comment]
This might be a xwayland issue at particular setup. Neverthless I haven't tried glx program for a while. I'll check.

**Comment by Cloudef** [comment]
Seems to work fine here indeed.

**Comment by Cloudef** [comment]
Confirmed mesa bug I guess.
